import type { Offer, RunState, Usher } from "@/lib/types";

function statusLabel(status: Offer["status"]): string {
  switch (status) {
    case "confirmed":
      return "Confirmed";
    case "declined":
      return "Declined";
    case "sent":
      return "Awaiting reply";
    case "queued":
      return "Queued";
    case "waitlisted":
      return "Waitlist";
    default:
      return "Proposed";
  }
}

export function renderCallsheet(state: RunState, crew: Usher[]): string {
  const brief = state.brief;
  if (!brief) return "# Call sheet\n\nNo brief yet.";
  const byId = new Map(crew.map((u) => [u.id, u]));
  const lines: string[] = [];

  lines.push(`# Call sheet: ${brief.name}`);
  lines.push("");
  lines.push(`- Venue: ${brief.verifiedVenue ?? brief.venue}${brief.verifiedVenue && brief.verifiedVenue !== brief.venue ? ` (coordinator stated "${brief.venue}")` : ""}`);
  lines.push(`- City: ${brief.city}`);
  lines.push(`- Dates: ${brief.dates.join(", ")}`);
  lines.push(`- Shift: ${brief.shiftStart} to ${brief.shiftEnd}, ${brief.hoursPerDay} hours`);
  lines.push(`- Rate: AED ${brief.rateAedPerHour.toFixed(2)} per hour`);
  if (brief.training) {
    lines.push(
      `- Training: ${brief.training.date}, ${brief.training.durationHours} hours, ${brief.training.mandatory ? "mandatory" : "optional"}`,
    );
  }
  lines.push(`- Transport: ${brief.transport}`);
  lines.push(`- Meals: ${brief.meals}`);
  if (brief.organiser) lines.push(`- Organiser: ${brief.organiser}`);
  if (brief.sources?.length) lines.push(`- Sources: ${brief.sources.slice(0, 4).join(" , ")}`);
  lines.push("");

  const confirmed = state.offers.filter((o) => o.status === "confirmed").length;
  const total = brief.positions.reduce((n, p) => n + p.needed, 0);
  lines.push(`Fill: ${confirmed} confirmed of ${total} slots, ${state.offers.length} offers out.`);
  lines.push("");

  for (const position of brief.positions) {
    const rows = state.offers.filter((o) => o.area === position.area);
    lines.push(`## ${position.area} (${rows.filter((r) => r.status === "confirmed").length} of ${position.needed})`);
    lines.push("");
    lines.push("| Usher | City | Phone | Status | Why |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const row of rows) {
      const u = byId.get(row.usherId);
      lines.push(
        `| ${u?.name ?? row.usherId} | ${u?.city ?? ""} | ${u?.phone ?? ""} | ${statusLabel(row.status)} | ${row.reason.replace(/\|/g, "/")} |`,
      );
    }
    lines.push("");
  }

  const errors = state.offers.filter((o) => o.error);
  if (errors.length) {
    lines.push("## Delivery problems");
    lines.push("");
    for (const e of errors.slice(0, 20)) {
      lines.push(`- ${byId.get(e.usherId)?.name ?? e.usherId}: ${e.error}`);
    }
    lines.push("");
  }

  lines.push(`Generated by the Callsheet agent at ${new Date().toISOString()}.`);
  return lines.join("\n");
}
